# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dockernextapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mynextcontainerregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_8b8c46a7d6174eadbf4e094fb520a7a1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_61180aec9fa04c52bb3b5673aeee4441 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mynextcontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8b8c46a7d6174eadbf4e094fb520a7a1 }}/nextjs13-docker:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dockernextapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_eb95d7346219415aa030e3e8aee6f1d2 }}
        images: 'mynextcontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8b8c46a7d6174eadbf4e094fb520a7a1 }}/nextjs13-docker:${{ github.sha }}'